### PR TITLE
Add simplified Chinese language file

### PR DESCRIPTION
**Pull request by kytrun**
# Description

Add simplified Chinese language file.

# Checklist:

In the [contribution guidelines](https://github.com/martinstoeckli/SilentNotes/blob/main/CONTRIBUTING.md) you can find more detailed instructions.

- [ ] I have added unit-tests, whenever this is possible with a reasonable amount of work
- [ ] My code follows the style guidelines of this project (StyleCop rules)
- [ ] I have commented all public functions
- [x] I have made corresponding changes to the localization files

### CODE REVIEW

**Comment by martinstoeckli** [comment]
Hello Kytrun

Thank you very much for your work, I would be very happy to include your Chinese translation. Do you think that you could also translate textes for future updates? From the moment when I distribute your translation, users will expect their language in future updates and not being able to provide it will be seen as a setback.

Another question, is the direction of reading (left to right) a problem with a Chinese translation?

If you would like to help in future, I would add you as a contributor, so you do not have to fork the repository.

Best regards:
Martin

**Comment by kytrun** [comment]
Hi Martin

Thanks for your great open source of SilentNotes and your approval for my translation. It will be my honor to be the future translator of simplified Chinese and I'd like to be. I will continuously do it with my best effort.

In addition, the direction of Chinese text is from left to right just like lots of other languages.

Best wishes,
Kytrun

**Comment by martinstoeckli** [comment]
Great, thank you! One more question, how important is it to distinguish between Lng.SilentNotes.zh-cn and just Lng.SilentNotes.zh, are those languages completely different, so they do not understand each other, or would the shorter name be sufficient?

**Comment by kytrun** [comment]
Because there are some regions where people use different versions of Chinese. For example there might be "zh-CN", "zh-TW", "zh-HK" corresponding to the China mainland, Taiwan and Hongkong.

I'm not sure if there will be other versions of Chinese added in the future so I kept the file extension as "zh-cn".

**Comment by martinstoeckli** [comment]
Thank you for the detailed explanation! As you already may have seen I merged the pull request and renamed the file to Lng.SilentNotes.zh . If there are no big differences, I would like to keep the more generic filename, as long as there are no important reasons to do otherwise.

**Comment by kytrun** [comment]
Fine, thank you.

**Pull request merged**
