### PR TITLE
Added fastlane description.

### PR DESCRIPTION
**Pull request by martinstoeckli**
Moved screenshots to the suitable fastlane directories.

### CODE REVIEW

**Review by martinstoeckli — COMMENTED** [review]
@IzzySoft - I'm ready to merge my fastlane informations, but I couldn't find all information I need. The history files for example are named by the version of the APK now (39.txt) and not the version of the GitHub version (5.5.0) is this correct? And about the size of the icon I could find nothing in the documentation, I choose a 64*64 png. The naming of the screenshots in the example are increasing numbers, is this a convention to define an order or are the names free? So many questions...

**Comment by IzzySoft** [comment]
> The history files for example are named by the version of the APK now (39.txt) and not the version of the GitHub version (5.5.0) is this correct?

Yes: it's `<versionCode>.txt` (while 5.5.0 would be `versionName` – I'd usually reference the `build.gradle` for this but you have none, and I'm not familiar with what you use here).

> about the size of the icon

Should be in my snippet (oh, only in the [Triple-T snippet](https://gitlab.com/snippets/1901490) it seems, most likely I could not find that reference in Fastlane docs). It's squared, max 512x512 and min 48x48, take your pick.

> The naming of the screenshots in the example are increasing numbers,

You can name them to your liking. Numbering just makes sure they are shown in the intended order.

**Comment by martinstoeckli** [comment]
Thanks you very much! I will soon publish a new version 39 and the repository already contains the fastlane files. I added the german full description, the changelogs and moved the screenshots to the suitable directories.

**Comment by IzzySoft** [comment]
Great! That will arrive in my repo automatically (I'll check right away whether metadata fit your new Fastlane additions). At F-Droid I can only trigger things, I cannot build your app not being familiar with its language etc (for now, the only ones I work on are Java and Kotlin projects, with a little help also Flutter sometimes)…

**Pull request merged**
