### PR TITLE
Feature: add note pin

### LINKED ISSUE #121: Feature request: Pin Note
One feature that could come in handy - pinning a note.  
For example: I have a note that's a to do list, so I need to keep it at the top of everything. But every time I add a new note, it gets put at the top (or bottom, which I don't really like) so after a couple notes the to do list is buried and I have to constantly drag it to the top.    

I assume you store the position of the notes on the grid in some way, so this could work by simply rendering those first (like a "always on top" thing), or having a separate grid for pinned notes (see picture).  

Here's a simple drawing on how it could look:
pin_note

It could be set either by a icon on the note:
Untitled-1
or in the note's menu bar/menu: 
Screenshot 2021-11-27 190425
  
Let me know what you think.
Cheers,
Jakub

### PR DESCRIPTION
**Pull request by Dizzap**
Add feature: pinning a note. Closes #121

### CODE REVIEW

**Comment by Dizzap** [comment]
Here's a sort-of working draft of the feature. 
Ran into a problem though - I check for moving an unpinned note in front of a pinned one (which user shouldn't be able to do) in `NoteRepositoryViewModel.MoveNote()`, but it only affects the collection of notes, not the UI, so the user can drag the note there and it will stay there untill reload. I cannot find a way to actually block the user from moving the note there, or moving the note manually after. Maybe some sort of refresh could work?
How to reproduce:
1. Pin a note 
2. Drag an unpinned note in front of the pinned one
3. The note will stay there, but the actual position in the collection is different, and will change after reload

**Comment by martinstoeckli** [comment]
While dragging, the GUI is in full control and notifies the ViewModel about changes, but the viewmodel cannot notify the View to refresh because this would interrupt the drag operation. It is hard to come by in a MVVM environment with HTML as GUI. I think in this case, the restriction of the drop targets must be solved in the View and unfortunately cannot be done in the ViewModel. I see two ways to solve the problem, the more I think about it, the first solution seems the better one:

1. If a note is dragged above a pinned one, it's probably the intention of the user to pin it as well, so we could leave the drag operation as it is and just set the pin state active. The same goes for the reverse action, a note which is dragged below an unpinned note, should probably become unpinned.
2. The sort library "sortable.js" can be modified, so that it can ask whether a certain target position is accepted or not, and prevent dragging into the region of un/pinned notes. I think there is a lot of work involved, and I'm not content with the current behaviour anyway, see #107 . This and because the next release will have a min Android version 6 (which can make use of the HTML5 drag&drop api), this solution may not be worth the invested time.

So what do you think?

**Comment by Dizzap** [comment]
The first solution is definitely the way to go, it's elegant and much easier to implement. Thanks for the input.

**Comment by Dizzap** [comment]
Ready for testing.
Feature set:
- pin button inside note, takes effect after "closing" the note
- when you pin a note, it moves to the first position and displays a pin icon
- when you unpin a note, it moves behind the last pinned note and hides a pin icon
- when you drag an unpinned note in front of a pinned note, it gets pinned automatically
- when you drag a pinned note behind an unpinned one, it get unpinned automatically
- new notes get added behind pinned notes

**Comment by martinstoeckli** [comment]
Thanks, I will test it as soon as I can find the time!

**Comment by Dizzap** [comment]
Thanks, that would be appreciated, mainly because I'm using it the way I intended it, which could miss some major problems.
I did a fairly thorough test on Windows and a basic test on Android, all seems to be working as intended. I did **not** however test on the minimal version of Android, since my project refuses to build for some reason.

If you find any problems, please let me know. In the meantime I'll check all the names, comments, formatting etc. to make sure all is up to standards.

**Comment by Dizzap** [comment]
Note: This will require to add translations for pin note icon tooltip. Key "note_pin".

**Pull request merged**
